name: Deploy on Dev Server

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.0] 

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Uncomment and modify this section for file copying if needed
      # - name: Copy files via SSH key
      #   uses: garygrossgarten/github-action-scp@release
      #   with:
      #     local: "./"
      #     remote: "/usr/project/beato-dev"
      #     host: ${{ secrets.DEV_HOST }}
      #     username: ${{ secrets.USER_NAME }}
      #     password: ${{ secrets.DEV_PASSWORD }}

      - name: Install dependencies
        run: npm install

      - name: Build and Restart Server
        run: |
            npm run build 
            pm2 restart diabetes-server