name: Deploy on Dev Server

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.0] 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: "16.10.0"


      - name: Install npm dependencies
        run: |
          npm install
      # Uncomment and modify this section for file copying if needed
      # - name: Copy files via SSH key
      #   uses: garygrossgarten/github-action-scp@release
      #   with:
      #     local: "./"
      #     remote: "/usr/project/beato-dev"
      #     host: ${{ secrets.DEV_HOST }}
      #     username: ${{ secrets.USER_NAME }}
      #     password: ${{ secrets.DEV_PASSWORD }}

      - name: Restart Server
        run: |
            pm2 restart diabetes-server